name: sarsys_ops_server
description: SARSys Ops server
version: 0.0.1
author: Kenneth Gulbrandsøy <kenneth@discoos.org>

environment:
  sdk: '>=2.9.0 <3.0.0'

publish_to: none

dependencies:
  grpc: ^2.8.0
  logging: ^0.11.4
  protobuf: ^1.1.0
  stack_trace: ^1.9.6
  collection_x:
    path: ../collection_x
  event_source_grpc:
    path: ../event_source_grpc
  sarsys_app_server:
    path: ../sarsys_app_server
  sarsys_tracking_server:
    path: ../sarsys_tracking_server


dev_dependencies:
  test: ^1.0.0
  aqueduct_test: ^1.0.0
  sarsys_ops_server_test:
    path: ../sarsys_ops_server_test
