name: event_source_grpc
description: Event Source Grpc library
version: 0.0.1
author: Kenneth Gulbrandsøy <kenneth@discoos.org>
homepage: https://github.com/DISCOOS/sarsys-backend

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  grpc: ^2.8.0
  protobuf: ^1.1.0
  fixnum: ^0.10.11
  stack_trace: ^1.9.6
  chunked_stream: ^1.2.0
  event_source:
    path: ../event_source


dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  event_source_test:
    path: ../event_source_test
  event_source_grpc_test:
    path: ../event_source_grpc_test
