name: sarsys_app_server
description: API consumed by SarSys apps
version: 0.0.1
author: DISCO Open Source <support@discoos.org>
homepage: https://github.com/DISCOOS/sarsys-backend

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  args: ^1.5.2
  uuid: ^2.0.2
  hive: ^1.1.1
  jose: ^0.1.2+1
  webfeed: ^0.4.2
  strings: ^0.1.2
  aqueduct: ^3.0.0
  equatable: ^1.0.1
  jaguar_jwt: ^2.1.6
  json_patch: ^2.0.0
  json_schema: ^2.2.1
  validators: ^2.0.0+1
  json_annotation: ^2.0.0
  sentry: ^3.0.1
  event_source:
    path: ../event_source
  sarsys_domain:
    path: ../sarsys_domain


dev_dependencies:
  test: ^1.0.0
  aqueduct_test: ^1.0.0
  build_runner: ^1.7.0
  json_serializable: ^2.0.0
