name: sarsys_http_core
description: SARSys server shared kernel
version: 0.0.1
author: Kenneth Gulbrandsøy <kenneth@discoos.org>
homepage: https://github.com/DISCOOS/sarsys-backend

environment:
  sdk: '>=2.9.0 <3.0.0'

dependencies:
  args: ^1.5.2
  uuid: ^2.0.2
  hive: ^1.1.1
  webfeed: ^0.4.2
  jose: ^0.2.1+1
  strings: ^0.1.2
  filesize: ^1.0.4
  equatable: ^1.0.1
  json_patch: ^2.0.0
  aqueduct: ^3.3.0+1
  json_schema: ^2.2.1
  stack_trace: ^1.9.6
  validators: ^2.0.0+1
  sentry: ^3.0.1
  event_source:
    path: ../event_source

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.6.0
  aqueduct_test: ^1.0.0


dependency_overrides:
  jose:
    #    path: ../../jose
    git:
      url: https://github.com/DISCOOS/jose.git
      ref: issue/10_only_throw_when_x509_only
