apiVersion: v1
kind: ServiceAccount
metadata:
  name: sarsys-user
  namespace: sarsys
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: sarsys
  name: ops-monitor
rules:
  - apiGroups: ["", "metrics.k8s.io"]
    resources: ["pods", "nodes"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows service
# account "sarsys-user" to read pods
# in the "sarsys" namespace.
kind: RoleBinding
metadata:
  name: read-pods
  namespace: sarsys
subjects:
  - kind: ServiceAccount
    name: sarsys-user
    namespace: sarsys
roleRef:
  kind: Role
  name: ops-monitor
  apiGroup: rbac.authorization.k8s.io