name: sarsys_tracking_server
description: SARSys tracking server
version: 0.0.1
author: Kenneth Gulbrandsøy <kenneth@discoos.org>

environment:
  sdk: '>=2.9.0 <3.0.0'

publish_to: none

dependencies:
  grpc: ^2.8.0
  logging: ^0.11.4
  protobuf: ^1.1.0
  fixnum: ^0.10.11
  sarsys_core:
    path: ../sarsys_core
  sarsys_domain:
    path: ../sarsys_domain
  event_source_grpc:
    path: ../event_source_grpc


dev_dependencies:
  test: ^1.0.0
  sarsys_tracking_server_test:
    path: ../sarsys_tracking_server_test
