name: sarsys_domain
description: SarSys Domain objects sourced from EventStore
version: 0.0.1
author: Kenneth Gulbrandsøy <kenneth@discoos.org>
homepage: https://github.com/DISCOOS/sarsys-backend

environment:
  sdk: '>=2.9.0 <3.0.0'

dependencies:
  json_annotation: ^3.1.0
  event_source:
    path: ../event_source

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  build_runner: ^1.7.0
  build_resolvers: ^1.3.11
  json_serializable: ^3.5.1
