name: sarsys_tracking_server_test
description: SARSys Tracking Server test support library
version: 1.0.0
author: Kenneth Gulbrandsøy <kenneth@discoos.org>
homepage: https://github.com/DISCOOS/sarsys-backend

environment:
  sdk: '>=2.9.0 <3.0.0'

dependencies:
  aqueduct_test: ^1.0.0
  event_source_test:
    path: ../event_source_test
  #  sarsys_domain:
  #    path: ../sarsys_domain
  #  sarsys_http_core:
  #    path: ../sarsys_http_core
#  sarsys_app_server:
#    path: ../sarsys_app_server
  sarsys_tracking_server:
    path: ../sarsys_tracking_server


dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.0.0
