name: sarsys_app_server_test
description: SARSys App Server test support library
version: 1.0.0
author: Kenneth Gulbrandsøy <kenneth@discoos.org>
homepage: https://github.com/DISCOOS/sarsys-backend

environment:
  sdk: '>=2.9.0 <3.0.0'

publish_to: none

dependencies:
  aqueduct_test: ^1.0.0
  collection_x:
    path: ../collection_x
  event_source_test:
    path: ../event_source_test
  sarsys_app_server:
    path: ../sarsys_app_server


dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.0.0
